name: gestalt
description: Simple Gestalt-style string similarity for Dart and Flutter.
version: 1.0.2
repository: https://github.com/shizongli94/gestalt-dart
homepage: https://github.com/shizongli94/gestalt-dart

environment:
  sdk: ^3.12.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
